# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_adicionar_senha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setWhatsThis("")
        MainWindow.setAutoFillBackground(False)
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labe_adc_senha = QtWidgets.QLabel(self.centralwidget)
        self.labe_adc_senha.setGeometry(QtCore.QRect(210, 90, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.labe_adc_senha.setFont(font)
        self.labe_adc_senha.setObjectName("labe_adc_senha")
        self.pushButton_salva = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_salva.setGeometry(QtCore.QRect(450, 300, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_salva.setFont(font)
        self.pushButton_salva.setStyleSheet("background: #0BAEE1; \n"
"border-radius: 10px;")
        self.pushButton_salva.setObjectName("pushButton_salva")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 300, 71, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background: rgb(156, 156, 156);\n"
"border-radius: 10px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_url = QtWidgets.QLabel(self.centralwidget)
        self.label_url.setGeometry(QtCore.QRect(140, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_url.setFont(font)
        self.label_url.setObjectName("label_url")
        self.label_nam_usuario = QtWidgets.QLabel(self.centralwidget)
        self.label_nam_usuario.setGeometry(QtCore.QRect(140, 210, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_nam_usuario.setFont(font)
        self.label_nam_usuario.setObjectName("label_nam_usuario")
        self.label_pswd_sit = QtWidgets.QLabel(self.centralwidget)
        self.label_pswd_sit.setGeometry(QtCore.QRect(360, 210, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_pswd_sit.setFont(font)
        self.label_pswd_sit.setObjectName("label_pswd_sit")
        self.label_categori = QtWidgets.QLabel(self.centralwidget)
        self.label_categori.setGeometry(QtCore.QRect(140, 280, 181, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_categori.setFont(font)
        self.label_categori.setObjectName("label_categori")
        self.lineEdit_sit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_sit.setGeometry(QtCore.QRect(130, 160, 401, 31))
        self.lineEdit_sit.setStyleSheet("border-style: outset;\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"")
        self.lineEdit_sit.setObjectName("lineEdit_sit")
        self.lineEdit_categori = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_categori.setGeometry(QtCore.QRect(130, 300, 201, 31))
        self.lineEdit_categori.setStyleSheet("border-style: outset;\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"")
        self.lineEdit_categori.setObjectName("lineEdit_categori")
        self.lineEdit_pswd_sit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_pswd_sit.setGeometry(QtCore.QRect(350, 230, 181, 31))
        self.lineEdit_pswd_sit.setStyleSheet("border-style: outset;\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"")
        self.lineEdit_pswd_sit.setObjectName("lineEdit_pswd_sit")
        self.lineEdit_nam_usuari = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_nam_usuari.setGeometry(QtCore.QRect(130, 230, 201, 31))
        self.lineEdit_nam_usuari.setStyleSheet("border-style: outset;\n"
"\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);\n"
"")
        self.lineEdit_nam_usuari.setObjectName("lineEdit_nam_usuari")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labe_adc_senha.setText(_translate("MainWindow", "Adicionar senha "))
        self.pushButton_salva.setText(_translate("MainWindow", "Salvar"))
        self.pushButton_2.setText(_translate("MainWindow", "cancelar"))
        self.label_url.setText(_translate("MainWindow", "URL:"))
        self.label_nam_usuario.setText(_translate("MainWindow", "Nome de usuário: "))
        self.label_pswd_sit.setText(_translate("MainWindow", "Senha site:"))
        self.label_categori.setText(_translate("MainWindow", "Categoria"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
