# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela_gerar_senha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_gerar_senha = QtWidgets.QLabel(self.centralwidget)
        self.label_gerar_senha.setGeometry(QtCore.QRect(210, 60, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_gerar_senha.setFont(font)
        self.label_gerar_senha.setObjectName("label_gerar_senha")
        self.label_background_cinz = QtWidgets.QLabel(self.centralwidget)
        self.label_background_cinz.setGeometry(QtCore.QRect(130, 180, 391, 181))
        self.label_background_cinz.setStyleSheet("background: rgb(156, 156, 156);\n"
"border-radius: 10px;")
        self.label_background_cinz.setText("")
        self.label_background_cinz.setObjectName("label_background_cinz")
        self.label_personaliza_senh = QtWidgets.QLabel(self.centralwidget)
        self.label_personaliza_senh.setGeometry(QtCore.QRect(150, 190, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_personaliza_senh.setFont(font)
        self.label_personaliza_senh.setObjectName("label_personaliza_senh")
        self.label_numer_caracteres = QtWidgets.QLabel(self.centralwidget)
        self.label_numer_caracteres.setGeometry(QtCore.QRect(150, 230, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_numer_caracteres.setFont(font)
        self.label_numer_caracteres.setObjectName("label_numer_caracteres")
        self.lineEdit_num_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_num_senha.setGeometry(QtCore.QRect(350, 230, 21, 20))
        self.lineEdit_num_senha.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"border-color: rgb(156, 156, 156);\n"
"")
        self.lineEdit_num_senha.setText("")
        self.lineEdit_num_senha.setObjectName("lineEdit_num_senha")
        self.checkBox_letra_maiuscula = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_letra_maiuscula.setGeometry(QtCore.QRect(150, 260, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_letra_maiuscula.setFont(font)
        self.checkBox_letra_maiuscula.setObjectName("checkBox_letra_maiuscula")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 290, 131, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_numero = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_numero.setGeometry(QtCore.QRect(150, 320, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_numero.setFont(font)
        self.checkBox_numero.setObjectName("checkBox_numero")
        self.label_senha_gerad = QtWidgets.QLabel(self.centralwidget)
        self.label_senha_gerad.setGeometry(QtCore.QRect(130, 120, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_senha_gerad.setFont(font)
        self.label_senha_gerad.setStyleSheet("background: rgb(156, 156, 156);\n"
"border-radius: 10px;")
        self.label_senha_gerad.setText("")
        self.label_senha_gerad.setObjectName("label_senha_gerad")
        self.pushButton_copiar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copiar.setGeometry(QtCore.QRect(360, 130, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_copiar.setFont(font)
        self.pushButton_copiar.setStyleSheet("background: #0BAEE1; \n"
"border-radius: 10px;")
        self.pushButton_copiar.setObjectName("pushButton_copiar")
        self.pushButton_gera = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_gera.setGeometry(QtCore.QRect(440, 130, 71, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_gera.setFont(font)
        self.pushButton_gera.setStyleSheet("background: #0BAEE1; \n"
"border-radius: 10px;")
        self.pushButton_gera.setObjectName("pushButton_gera")
        self.pushButton_copiar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copiar_2.setGeometry(QtCore.QRect(260, 380, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_copiar_2.setFont(font)
        self.pushButton_copiar_2.setStyleSheet("background: #0BAEE1; \n"
"border-radius: 10px;")
        self.pushButton_copiar_2.setObjectName("pushButton_copiar_2")
        self.label_background_cinz.raise_()
        self.label_gerar_senha.raise_()
        self.label_personaliza_senh.raise_()
        self.label_numer_caracteres.raise_()
        self.lineEdit_num_senha.raise_()
        self.checkBox_letra_maiuscula.raise_()
        self.checkBox_2.raise_()
        self.checkBox_numero.raise_()
        self.label_senha_gerad.raise_()
        self.pushButton_copiar.raise_()
        self.pushButton_gera.raise_()
        self.pushButton_copiar_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_gerar_senha.setText(_translate("MainWindow", "Gerar senha segura"))
        self.label_personaliza_senh.setText(_translate("MainWindow", "Personalizar senha:"))
        self.label_numer_caracteres.setText(_translate("MainWindow", "Número de caracteres da senha:"))
        self.checkBox_letra_maiuscula.setText(_translate("MainWindow", "Letras maiúsculas"))
        self.checkBox_2.setText(_translate("MainWindow", "Letras minúsculas"))
        self.checkBox_numero.setText(_translate("MainWindow", "Números"))
        self.pushButton_copiar.setText(_translate("MainWindow", "Copiar"))
        self.pushButton_gera.setText(_translate("MainWindow", "Gerar"))
        self.pushButton_copiar_2.setText(_translate("MainWindow", "Gerar senha"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
