# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\tela_criarConta.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 623)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_criar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_criar.setGeometry(QtCore.QRect(330, 430, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.botao_criar.setFont(font)
        self.botao_criar.setStyleSheet("background: #0BAEE1;\n"
"border-radius: 10px;")
        self.botao_criar.setObjectName("botao_criar")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(30, 10, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.Logo.setFont(font)
        self.Logo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Logo.setObjectName("Logo")
        self.lineEdit_email = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_email.setGeometry(QtCore.QRect(210, 210, 401, 41))
        self.lineEdit_email.setStyleSheet("border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 10px;\n"
"border-color: rgb(156, 156, 156);")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.lineEdit_senha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_senha.setGeometry(QtCore.QRect(210, 290, 401, 41))
        self.lineEdit_senha.setStyleSheet("border-radius: 10px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(156, 156, 156);")
        self.lineEdit_senha.setObjectName("lineEdit_senha")
        self.label_email = QtWidgets.QLabel(self.centralwidget)
        self.label_email.setGeometry(QtCore.QRect(220, 180, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.label_senha = QtWidgets.QLabel(self.centralwidget)
        self.label_senha.setGeometry(QtCore.QRect(220, 260, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_senha.setFont(font)
        self.label_senha.setObjectName("label_senha")
        self.label_ciarConta = QtWidgets.QLabel(self.centralwidget)
        self.label_ciarConta.setGeometry(QtCore.QRect(340, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_ciarConta.setFont(font)
        self.label_ciarConta.setObjectName("label_ciarConta")
        self.lineEdit_confirmarSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_confirmarSenha.setGeometry(QtCore.QRect(210, 370, 401, 41))
        self.lineEdit_confirmarSenha.setStyleSheet("border-radius: 10px;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-color: rgb(156, 156, 156);")
        self.lineEdit_confirmarSenha.setObjectName("lineEdit_confirmarSenha")
        self.label_confirmarSenha = QtWidgets.QLabel(self.centralwidget)
        self.label_confirmarSenha.setGeometry(QtCore.QRect(220, 340, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_confirmarSenha.setFont(font)
        self.label_confirmarSenha.setObjectName("label_confirmarSenha")
        self.botao_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_voltar.setGeometry(QtCore.QRect(660, 30, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.botao_voltar.setFont(font)
        self.botao_voltar.setStyleSheet("background: #0BAEE1;\n"
"border-radius: 10px;")
        self.botao_voltar.setObjectName("botao_voltar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 812, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.botao_criar.setText(_translate("MainWindow", "Criar"))
        self.Logo.setText(_translate("MainWindow", "PassKay"))
        self.label_email.setText(_translate("MainWindow", "E-mail:"))
        self.label_senha.setText(_translate("MainWindow", "Senha:"))
        self.label_ciarConta.setText(_translate("MainWindow", "Criar conta"))
        self.label_confirmarSenha.setText(_translate("MainWindow", "Confirmar senha:"))
        self.botao_voltar.setText(_translate("MainWindow", "Voltar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
